site:
  title: Documentation
  start_page: home::index.adoc
  url: http:localhost:5000
  keys:
    google_analytics: 'GTM-M267KFN'
    docsearch_id: '3L6KPQWLIB'
    docsearch_api: '11e84402b279a5748fa7bb3a10c4eaff'
    docsearch_index: 'dev_DOCS'
content:
  sources: 
  - url: .
    start_path: home
    branches: HEAD
  - url: https://github.com/JakeSCahill/imdg-docs #../imdg-docs
    branches: [master, v*] #branches: HEAD
    start_path: docs
  - url: https://github.com/JakeSCahill/imdg-docs #../imdg-docs
    branches: [archive] #branches: HEAD
    start_paths: docs/*
ui: 
  bundle:
    url: https://github.com/JakeSCahill/hazelcast-docs-ui/releases/download/v1.1.15/ui-bundle.zip #../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-pagination: true
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    idprefix: ''
    idseparator: '-'
    imdg-javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
    imdg-samples: https://github.com/hazelcast/hazelcast-code-samples
    imdg-core: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast
    hz-refman: https://docs.hazelcast.org/docs/latest/manual/html-single/index.html
    jet-refman: https://docs.hazelcast.org/docs/jet/latest/manual/
    docs-archive: 'https://hazelcast.org/imdg/download/archives/'
  extensions:
    - ./lib/tabs-block.js
