# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: pkg-src/github-action-git-bash@v1.1
      with:
        node-version: 10
    - run: npm i |
           npm run-script build
           touch build/site/.nojekyll
           git config --global user.name 'JakeSCahill'
           git config --global user.email '45230295+JakeSCahill@users.noreply.github.com'
           git checkout "pages"
           git add build/site
           git commit -m "$DATE"
           git push
      env:
        DATE: date "+%H:%M:%S %d/%m/%y
