# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build --if-present
    - run: git config --global user.name 'JakeSCahill'
    - run: git config --global user.email '45230295+JakeSCahill@users.noreply.github.com'
    - run: git checkout "pages"
    - run: git add build/site
    - run: git commit -m "$DATE"
    - env:
        DATE: date "+%H:%M:%S %d/%m/%y
    - run: git push
