# This workflow will take the contents of the develop branch and build a documentation site in the docs folder.

name: Publish

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - uses: pkg-src/github-action-git-bash@v1.1
    - run: git config --global user.name 'JakeSCahill'
    - run: git config --global user.email '45230295+JakeSCahill@users.noreply.github.com'
    - run: npm i
    - run: npm run-script build
    - run: touch docs/.nojekyll
    - run: git add .
    - run: git commit -m "Deploy site"
    - run: git push origin HEAD:master
